#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/marla .
docker build -t ${REPO}/marla:${TAG} .

echo Built ${REPO}/marla:${TAG}
